### ISSUE TITLE
Создать необходимые контроллеры

### ISSUE THREAD

**Issue by M0untain13** [TheoremN1/Coins#8]

**Comment by wisetreee** [comment]
/api/getBalance - GET-запрос, получение с сервера баланса коинов текущего пользователя
/api/getAchievements - GET-запрос, получение с сервера списка всех достижений, за которые выдаются коины
/api/getApplications - GET-запрос, получение с сервера всех заявок текущего пользователя
/api/submitCoinApplication - POST-запрос, отправка заявки на коины на сервер
/api/submitMerchApplication - POST-запрос, отправка заявки на мерч на сервер
P.S Запросы по заявкам при желании можно объединить в "/api/submitApplication", в таком случае контроллер должен сам определить тип входящей заявки

**Comment by M0untain13** [comment]
GET    /balance
http://localhost:9009/balance?id=1
PUT    /balance
http://localhost:9009/balance?id=2&action=plus&amount=30

GET    /users
http://localhost:9009/users?id=1
POST   /users
http://localhost:9009/users?username=sdrn1k&name=Danil&surname=Zol&role=user
PUT    /users
http://localhost:9009/users?id=1&name=Y&surname=N
DELETE /users
http://localhost:9009/users?id=1

GET    /requests
POST   /requests
DELETE /requests

GET    /achievements
http://localhost:9009/achievements
